apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "3600"

    volumeMounts: 
      - mountPath: /inside_container_folder
        name: data-volume-name

  volumes:
     - name: data-volume-name
       persistentVolumeClaim:
          claimName: nfsclaim 
