apiVersion: v1
kind: Service
metadata:
  name: web-service
  resourceVersion: "1087"
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp-mysql
  type: NodePort
