apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: busybox
    name: busybox
  spec:
    containers:
    - command:
      - sleep
      - "10000"
      image: busybox:1.28
      name: busybox
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: redis
    name: redis
  spec:
    containers:
    - image: redis:alpine
      name: redis
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""