apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
      name: webapp-mysql
    name: webapp-mysql
spec:
    replicas: 1
    selector:
      matchLabels:
        name: webapp-mysql
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          name: webapp-mysql
        name: webapp-mysql
      spec:
        containers:
        - env:
          - name: DB_Host
            value: mysql-service
          - name: DB_User
            value: root
          - name: DB_Password
            value: paswrd
          image: mmumshad/simple-webapp-mysql
          imagePullPolicy: Always
          name: webapp-mysql
          ports:
          - containerPort: 8080
            protocol: TCP
