apiVersion: v1
kind: Pod
metadata:
  name: writepod
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command:
      - sleep
      - "10000"

    volumeMounts:
      - mountPath: /data
        name: data-volume-name

  volumes:
     - name: data-volume-name
       persistentVolumeClaim:
          claimName: nfsclaim